require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Layout/BlockEndNewline:
  Exclude:
    - spec/**/*_spec.rb

Layout/MultilineBlockLayout:
  Exclude:
    - spec/**/*_spec.rb

Layout/SpaceInsideBlockBraces:
  Exclude:
    - spec/**/*_spec.rb

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Naming/HeredocDelimiterNaming:
  Enabled: false

Rails/Blank:
  UnlessPresent: false

Rails/Delegate:
  Enabled: false

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb

Style/BlockDelimiters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Exclude:
    - app/controllers/**/*.rb

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - db/seeds.rb
    - spec/**/*_spec.rb

AllCops:
  NewCops: enable

  Exclude:
    - bin/bundle
    - bin/webpack
    - bin/webpack-dev-server
    - bin/yarn
    - db/migrate/*.rb
    - config/puma.rb
    - config/spring.rb
    - db/schema.rb
    - vendor/**/*
