Layout/SpaceInsideBlockBraces:
  Exclude:
    - spec/**/*_spec.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - db/seeds.rb

AllCops:
  NewCops: enable

  Exclude:
    - config/puma.rb
    - config/spring.rb
    - db/schema.rb
